variables:
  PROJECT_PIPELINE_NAME: 'xxf'
  PROJECT_DIR: '/opt/xxf'

stages:
  - build
  - deploy

workflow:
  name: '$PROJECT_PIPELINE_NAME'
  rules:
  #  - if: $CI_COMMIT_TAG
   #   when: always
    - if: $CI_COMMIT_BRANCH == 'master'
      when: always

package:
  stage: build
  script:
   - npm install
   - npm run build
   - mv -f ./dist/ $PROJECT_DIR/tmp/dist/

delop:
  stage: deploy
  script:
   - cd $PROJECT_DIR
   - mv -f ./dist/ ./dist$CI_PIPELINE_CREATED_AT/
   - mv -f ./tmp/dist/ ./dist/
